services:
  db:
    image: postgres:18-alpine
    container_name: monkworld_db
    environment:
      POSTGRES_DB: monkworld
      POSTGRES_USER: monk
      POSTGRES_PASSWORD: monkpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monk -d monkworld"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
