name: Perl Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Perl Tests
    runs-on: ubuntu-latest
    container:
      image: perl:5.42
      env:
        MONKWORLD_PG_URL: postgresql://test:test@postgres:5432/test

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        # Add health checks
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Perl version
        run: |
          perl -v

      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - App::cpanminus

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y libpq-dev

      - name: Install Perl dependencies
        run: |
          cpanm --installdeps --notest .

      - name: Run tests
        env:
          MONKWORLD_AUTH_TOKEN: ${{ secrets.MONKWORLD_AUTH_TOKEN }}
        run: |
          prove -lr
