name: Perl Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Perl Tests
    runs-on: ubuntu-latest
    container:
      image: perl:5.42-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Perl version
        run: |
          perl -v

      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - App::cpanminus

      - name: Install dependencies
        run: |
          cpanm --local-lib=~/perl5 --installdeps --notest .

      - name: Run tests
        env:
          PERL5LIB: ${{ github.workspace }}/lib:~/perl5/lib/perl5
        run: |
          prove -lvr
